# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    # runs-on: windows-latest # 运行环境为最新版 Ubuntu

    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: 检出最新代码 # step1 获取源码
        uses: actions/checkout@v4 # 使用 actions/checkout@v4
        with:
          persist-credentials: false
      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装 node modules 依赖 # step3 name
        run: npm install # 安装 node modules 相关依赖

      - name: Build
        run: npm run build
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Publish
        run: npm publish .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
